name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (no actual publish)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Build
        run: npm run build
      
      - name: Lint
        run: npm run lint

  publish:
    needs: test
    runs-on: macos-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Get version
        id: version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Publish to NPM - xc-mcp (primary)
        if: ${{ github.event_name == 'release' || github.event.inputs.dry_run == 'false' }}
        run: |
          echo "Publishing xc-mcp@${{ steps.version.outputs.version }}"
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish to NPM - xcmcp (alias)
        if: ${{ github.event_name == 'release' || github.event.inputs.dry_run == 'false' }}
        run: |
          echo "Publishing xcmcp@${{ steps.version.outputs.version }}"
          # Update package name for alias publish
          npm pkg set name=xcmcp
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish to NPM - xcode-mcp (alias)
        if: ${{ github.event_name == 'release' || github.event.inputs.dry_run == 'false' }}
        run: |
          echo "Publishing xcode-mcp@${{ steps.version.outputs.version }}"
          # Update package name for alias publish
          npm pkg set name=xcode-mcp
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Dry Run Summary
        if: ${{ github.event.inputs.dry_run == 'true' }}
        run: |
          echo "🚀 Dry run complete! Would have published:"
          echo "  - xc-mcp@${{ steps.version.outputs.version }}"
          echo "  - xcmcp@${{ steps.version.outputs.version }}"
          echo "  - xcode-mcp@${{ steps.version.outputs.version }}"