name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Build project
      run: npm run build
      
    - name: Create release package
      run: |
        # Create a release package with just the necessary files
        mkdir -p release-package
        cp -r dist/ release-package/
        cp package.json release-package/
        cp package-lock.json release-package/
        cp README.md release-package/
        cp CLAUDE.md release-package/
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## XC-MCP Release ${{ github.ref }}
          
          ### Features
          - Intelligent Xcode command-line tools with progressive disclosure
          - Smart caching system (1-hour default)
          - Performance tracking and optimization
          - Token overflow prevention for large outputs
          
          ### Installation
          ```bash
          npm install -g xc-mcp
          ```
          
          ### Usage
          Add to your MCP client configuration:
          ```json
          {
            "mcpServers": {
              "xc-mcp": {
                "command": "node",
                "args": ["/path/to/xc-mcp/dist/index.js"]
              }
            }
          }
          ```
        draft: false
        prerelease: false